name: company_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  file_picker: ^9.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl_phone_number_input: ^0.7.4
  pinput: ^5.0.1
  universal_html: ^2.2.4
  go_router: ^14.8.1
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    
flutter_web:
  uses-material-design: true
  web-renderer: html